name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
      - name: Zip sam build
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r aws-sam.zip README.md .aws-sam
      - name: Upload sam build
        uses: actions/upload-artifact@v2
        with:
          name: aws-sam
          path: aws-sam.zip
  publish-to-s3:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        include:
          - region: cmh
            aws_region: us-east-2
          - region: dub
            aws_region: eu-west-1
          - region: iad
            aws_region: us-east-1
          - region: syd
            aws_region: ap-southeast-2
    steps:
      - name: Download sam build
        uses: actions/download-artifact@v2
        with:
          name: aws-sam
      - name: Unzip sam build
        uses: montudor/action-zip@v0.1.0
        with:
          args: unzip -qq aws-sam.zip
      - name: sam package (${{ matrix.region }})
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "package --output-template-file /dev/null --s3-bucket truss-eks-auto-drain-${{ matrix.region }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ matrix.aws_region }}
