name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
      - name: sam package (cmh)
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "package --output-template-file packaged.yaml --s3-bucket truss-eks-auto-drain-cmh"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.UPLOAD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
