name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
