name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
      - name: Upload sam build
        uses: actions/upload-artifact@v2
        with:
          name: aws-sam
          path: .aws-sam
  publish-to-s3:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        include:
          - region: cmh
            aws_region: us-east-2
          - region: dub
            aws_region: eu-west-1
          - region: iad
            aws_region: us-east-1
          - region: syd
            aws_region: ap-southeast-2
    steps:
      - name: Download sam build
        uses: actions/download-artifact@v2
        with:
          name: aws-sam

      - name: sam package (${{ matrix.region }})
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "package --output-template-file /dev/null --s3-bucket truss-eks-auto-drain-${{ matrix.region }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $${ matrix.aws_region }}
      # - name: sam package (DUB)
      #   uses: TractorZoom/sam-cli-action@master
      #   with:
      #     sam_command: "package --output-template-file /dev/null --s3-bucket truss-eks-auto-drain-dub"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: eu-west-1
      # - name: sam package (IAD)
      #   uses: TractorZoom/sam-cli-action@master
      #   with:
      #     sam_command: "package --output-template-file /dev/null --s3-bucket truss-eks-auto-drain-iad"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
      # - name: sam package (SYD)
      #   uses: TractorZoom/sam-cli-action@master
      #   with:
      #     sam_command: "package --output-template-file /dev/null --s3-bucket truss-eks-auto-drain-syd"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ap-southeast-2
